### ISSUE TITLE
useCurrentLocation: false throws failed asertion

### ISSUE THREAD

**Issue by nstrelow** [fysoul17/google_maps_place_picker#11]
**Describe the bug**
Using the example in this repo.
Setting useCurrentLocation to false throws a rendering error.

**To Reproduce**
1. Set useCurrentLocation to false
2. Open Placepicker via button

**Error log**
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building GoogleMapPlacePicker(dirty):
'package:flutter/src/rendering/box.dart': Failed assertion: line 1705 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
                 (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  PlacePicker file:///C:/Users/nilss/projects/google_maps_place_picker/example/lib/main.dart:76:32
When the exception was thrown, this was the stack: 
#2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart:1705:18)
#3      RenderBox.size (package:flutter/src/rendering/box.dart:1711:6)
#4      GoogleMapPlacePicker._buildMapIcons (package:google_maps_place_picker/src/google_map_place_picker.dart:354:28)
#5      GoogleMapPlacePicker.build (package:google_maps_place_picker/src/google_map_place_picker.dart:127:9)
#6      StatelessElement.build (package:flutter/src/widgets/framework.dart:4397:28)
```

**Flutter Doctor -v**
```
[√] Flutter (Channel beta, v1.14.6, on Microsoft Windows [Version 10.0.19569.1000], locale de-DE)
    • Flutter version 1.14.6 at C:\Users\nilss\flutter
    • Framework revision fabeb2a16f (4 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\nilss\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-R, build-tools 29.0.3
    • ANDROID_SDK_ROOT = C:\Users\nilss\AppData\Local\Android\Sdk
    • Java binary at: C:\Users\nilss\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6137316\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Android Studio (version 3.6)
    • Android Studio at C:\Users\nilss\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\192.6186006
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (3 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
```

**Comment by fysoul17** [comment]
Thanks for reporting. 

The bug has been fixed. Please update to version 0.7.0.

**Comment by nstrelow** [comment]
Awesome, thanks for the quick fix :D

**Comment by fysoul17** [comment]
@nstrelow  No problem ;)
