### ISSUE TITLE
Search TextField location doesnt find the address still working...

### ISSUE THREAD

**Issue by wytex** [fysoul17/google_maps_place_picker#114]
I have setting up the plugin and everything is working search form field apart.
I can get current location
I can pick Address with picker but I can't search for location with text field.
I just used simply method to pick it:

```
ElevatedButton(onPressed: (){
                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (context) => PlacePicker(
                            apiKey: 'mycurrentAPI', // Put YOUR OWN KEY here.
                            onPlacePicked: (result) {
                              selectedPlace = result;
                              print(result);
                              Navigator.of(context).pop();
                            },
                            initialPosition: _ShipmentCreatorScreenState.kInitialPosition,
                            useCurrentLocation: true,
                          ),
                        ),
                      );
                    }, child: Text('Select an Address')),

```
I dont get any error just the circularProgress indicator is working infinitely when I start typing a location....
as per picture...
![Screenshot_1617361259](https://user-images.githubusercontent.com/60034256/113410385-9305ec00-93b3-11eb-93c3-182610a35839.png)

**Comment by wytex** [comment]
Nobody here answer to the issue?

**Comment by t-kietzmann** [comment]
Nearly the same issue with 2.0.0-nullsafety.3 on Flutter 2.0.4


E/flutter (25056): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'String' in type cast
E/flutter (25056): #0      _$StructuredFormattingFromJson
package:google_maps_webservice/src/places.g.dart:426
E/flutter (25056): #1      new StructuredFormatting.fromJson
package:google_maps_webservice/src/places.dart:1004
E/flutter (25056): #2      _$PredictionFromJson
package:google_maps_webservice/src/places.g.dart:375
E/flutter (25056): #3      new Prediction.fromJson
package:google_maps_webservice/src/places.dart:934
E/flutter (25056): #4      _$PlacesAutocompleteResponseFromJson.<anonymous closure>
package:google_maps_webservice/src/places.g.dart:341
E/flutter (25056): #5      MappedListIterable.elementAt (dart:_internal/iterable.dart:411:31)

E/flutter (25056): #6      ListIterator.moveNext (dart:_internal/iterable.dart:340:26)
E/flutter (25056): #7      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
E/flutter (25056): #8      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
E/flutter (25056): #9      new List.of (dart:core-patch/array_patch.dart:50:28)
E/flutter (25056): #10     ListIterable.toList (dart:_internal/iterable.dart:211:44)
E/flutter (25056): #11     _$PlacesAutocompleteResponseFromJson
package:google_maps_webservice/src/places.g.dart:342
E/flutter (25056): #12     new PlacesAutocompleteResponse.fromJson
package:google_maps_webservice/src/places.dart:894
E/flutter (25056): #13     GoogleMapsPlaces._decodeAutocompleteResponse
package:google_maps_webservice/src/places.dart:531
E/flutter (25056): #14     GoogleMapsPlaces.autocomplete
package:google_maps_webservice/src/places.dart:171
E/flutter (25056): <asynchronous suspension>
E/flutter (25056): #15     AutoCompleteSearchState._performAutoCompleteSearch
package:google_maps_place_picker/src/autocomplete_search.dart:280
E/flutter (25056): <asynchronous suspension>

**Comment by wytex** [comment]
did you try to enable place API in google cloud console?

**Comment by eazypizzy** [comment]
please help similar issue. Already enabled places api on google console. Still nothing

**Comment by loftrix** [comment]
Make sure you have billing enabled on your account because apis like places and geocoding requires you to enable billing

**Comment by saad3344555** [comment]
Make sure you have enabled billing because apis like geocoding and places requires billing to be enabled.
