### ISSUE TITLE
Search location is not working

### ISSUE THREAD

**Issue by manpreetpatil** [fysoul17/google_maps_place_picker#121]
When i search any location and select the address. It reload the map again on my current location. In console I'm getting following error

[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method camera#animate on channel plugins.flutter.io/google_maps_1)
E/flutter ( 6856): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 6856): <asynchronous suspension>
E/flutter ( 6856): #1      _PlacePickerState._moveTo (package:google_maps_place_picker/src/place_picker.dart:346:5)
E/flutter ( 6856): <asynchronous suspension>
E/flutter ( 6856): #2      _PlacePickerState._pickPrediction (package:google_maps_place_picker/src/place_picker.dart:337:5)
E/flutter ( 6856): <asynchronous suspension>

Please help me..

**Comment by narayanvyas** [comment]
Any updates on this issue?
