### ISSUE TITLE
🐛 Map not animating to the location on search.

### ISSUE THREAD

**Issue by uV3301** [fysoul17/google_maps_place_picker#125]
**Describe the bug**
When a user tries to search on the search bar, he either enters or choose the location from the suggestions below, the maps refreshes for a bit and then just stays where it was before. The result gets updated but the map does not animate to the location selected.

**To Reproduce**
I'm providing a gist to the dart file where I'm using the package
https://gist.github.com/uV3301/a01b8fb3111c97673f13ff9be861ad04

**Expected behavior**
The expected behavior should be that after the search selection, the map should animate to the query location.

**Screenshots**
<img src="https://user-images.githubusercontent.com/43047036/121736866-c41e3d80-cb15-11eb-8b24-649245e5697f.png" alt="ss01" width="30%" height="60%" />
<img src="https://user-images.githubusercontent.com/43047036/121736903-cf716900-cb15-11eb-930f-7dff40b543e8.png" alt="ss01" width="30%" height="60%" />
<img src="https://user-images.githubusercontent.com/43047036/121736830-b2d53100-cb15-11eb-90c7-2286b85cf74f.png" alt="ss01" width="30%" height="60%" />

**Flutter Doctor -v**
```
[✓] Flutter (Channel stable, 2.2.0, on Linux, locale en_IN)
    • Flutter version 2.2.0 at /home/uv3301/snap/flutter/common/flutter
    • Framework revision b22742018b (4 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/uv3301/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/uv3301/Applications/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /home/uv3301/Applications/android-studio
    • Flutter plugin version 55.1.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 •
      Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.

```
**Additional context**
Additionally the error on console is such : 
```
E/flutter (16385): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method camera#animate on channel plugins.flutter.io/google_maps_3)
E/flutter (16385): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (16385): <asynchronous suspension>
E/flutter (16385): #1      _PlacePickerState._moveTo (package:google_maps_place_picker/src/place_picker.dart:346:5)
E/flutter (16385): <asynchronous suspension>
E/flutter (16385): #2      _PlacePickerState._pickPrediction (package:google_maps_place_picker/src/place_picker.dart:337:5)
E/flutter (16385): <asynchronous suspension>
E/flutter (16385): 
I/flutter (16385): state: SearchingState.Idle, isSearchBarFocused: false
```

**Comment by haroonkhan335** [comment]
Experiencing the same issues..

Any solution you have found already?

**Comment by uV3301** [comment]
@haroonkhan335  No mate, didn't find anything yet. <br> @fysoul17 please look at the issue.

**Comment by interpretme** [comment]
This issue is only occurring when using custom widgets for floatingCard/Pin. As a solution --> 

I have created a new class, with `PlacePicker` itself, `PlacePickerCustom` and used it with `AutomaticKeepAliveClientMixin`, 

`
class PlacePickerCustom extends StatefulWidget {
  final Function(PickResult) onPlacePicked;
  final LatLng initialPosition;

  const PlacePickerCustom({Key key, this.onPlacePicked, this.initialPosition})
      : super(key: key);
  @override
  _PlacePickerCustomState createState() => _PlacePickerCustomState();
}

class _PlacePickerCustomState extends BaseState<PlacePickerCustom>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return PlacePicker(....)`
    
 It resolves the issue while selecting the address from `autoCompleteText`.
 https://stackoverflow.com/questions/59693451/flutter-googlemap-in-a-pageview-build-only-once

**Comment by Milinda1313** [comment]
https://stackoverflow.com/a/72052990/8631092

issue solved from this fix
