### ISSUE TITLE
select location from search result

### ISSUE THREAD

**Issue by hennonoman** [fysoul17/google_maps_place_picker#44]
when I choose a place from search result sometimes animate to my current location not to what I selected. 
if I do it again it will animate to the selected place.

**Comment by fysoul17** [comment]
I don't quite understand the issue.
Could you provide more information such as a reproducing scenario or gif screenshot, etc? (It is good to use bug report template tho)

**Comment by hennonoman** [comment]
First step this my current location:

![image](https://user-images.githubusercontent.com/25689733/84998312-56387380-b158-11ea-83c1-86afbf6b02e5.png)


Second step  I click on one of the results

![image](https://user-images.githubusercontent.com/25689733/84998233-3bfe9580-b158-11ea-8ad0-dc0fa831b494.png)



Third step after i choose a new location from serach box it returns me to my current location
![image](https://user-images.githubusercontent.com/25689733/84998551-a7e0fe00-b158-11ea-9904-9eb5f4fbb19c.png)

**Comment by easysoft-mobility** [comment]
Hello !
Everytime I search for a place and I choose one, I get the below error in console all the time.
I'm using your lib in my production app so please assist... Thank !

`E/flutter (  983): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method camera#animate on channel plugins.flutter.io/google_maps_6)

E/flutter (  983): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)

E/flutter (  983): <asynchronous suspension>
E/flutter (  983): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (  983): #2      MethodChannelGoogleMapsFlutter.animateCamera (package:google_maps_flutter_platform_interface/src/method_channel/method_channel_google_maps_flutter.dart:288:10)
E/flutter (  983): #3      GoogleMapController.animateCamera (package:google_maps_flutter/src/controller.dart:160:39)
E/flutter (  983): #4      _PlacePickerState._moveTo (package:google_maps_place_picker/src/place_picker.dart:300:22)
E/flutter (  983): #5      _PlacePickerState._pickPrediction (package:google_maps_place_picker/src/place_picker.dart:290:11)
E/flutter (  983): <asynchronous suspension>
E/flutter (  983): #6      _PlacePickerState._buildSearchBar.<anonymous closure> (package:google_maps_place_picker/src/place_picker.dart:242:17)
E/flutter (  983): #7      AutoCompleteSearchState._buildPredictionOverlay.<anonymous closure>.<anonymous closure> (package:google_maps_place_picker/src/autocomplete_search.dart:272:32)
E/flutter (  983): #8      PredictionTile.build.<anonymous closure> (package:google_maps_place_picker/src/components/prediction_tile.dart:21:16)
E/flutter (  983): #9      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:772:19)
E/flutter (  983): #10     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:855:36)
E/flutter (  983): #11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (  983): #12     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (  983): #13     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (  983): #14     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter (  983): #15     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter (  983): #16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (  983): #17     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (  983): #18     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (  983): #19     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (  983): #20     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (  983): #21     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (  983): #22     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (  983): #23     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (  983): #24     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (  983): #25     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (  983): #26     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (  983): #27     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (  983): #28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (  983): #29     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (  983): #30     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)`

**Comment by Milinda1313** [comment]
https://stackoverflow.com/a/72052990/8631092

issue solved from this fix
