### ISSUE TITLE
Place searching from searchbar: PlacePicker fail to navigate to selected place with error "MissingPluginException: camera#animate"

### ISSUE THREAD

**Issue by easysoft-mobility** [fysoul17/google_maps_place_picker#56]
**Describe the bug**
Hello !
Everytime I search for a place and I choose one, I get the below error in console all the time.
I'm using your lib in my production app so please assist... Thank !

`E/flutter ( 983): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method camera#animate on channel plugins.flutter.io/google_maps_6)

E/flutter ( 983): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)

E/flutter ( 983):
E/flutter ( 983): #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 983): #2 MethodChannelGoogleMapsFlutter.animateCamera (package:google_maps_flutter_platform_interface/src/method_channel/method_channel_google_maps_flutter.dart:288:10)
E/flutter ( 983): #3 GoogleMapController.animateCamera (package:google_maps_flutter/src/controller.dart:160:39)
E/flutter ( 983): #4 _PlacePickerState._moveTo (package:google_maps_place_picker/src/place_picker.dart:300:22)
E/flutter ( 983): #5 _PlacePickerState._pickPrediction (package:google_maps_place_picker/src/place_picker.dart:290:11)
E/flutter ( 983):
E/flutter ( 983): #6 _PlacePickerState._buildSearchBar. (package:google_maps_place_picker/src/place_picker.dart:242:17)
E/flutter ( 983): #7 AutoCompleteSearchState._buildPredictionOverlay.. (package:google_maps_place_picker/src/autocomplete_search.dart:272:32)
E/flutter ( 983): #8 PredictionTile.build. (package:google_maps_place_picker/src/components/prediction_tile.dart:21:16)
E/flutter ( 983): #9 _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:772:19)
E/flutter ( 983): #10 _InkResponseState.build. (package:flutter/src/material/ink_well.dart:855:36)
E/flutter ( 983): #11 GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 983): #12 TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter ( 983): #13 BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter ( 983): #14 BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter ( 983): #15 PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter ( 983): #16 PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 983): #17 PointerRouter._dispatchEventToRoutes. (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 983): #18 _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 983): #19 PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 983): #20 PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 983): #21 GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 983): #22 GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 983): #23 GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 983): #24 GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 983): #25 GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 983): #26 _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter ( 983): #27 _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 983): #28 _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter ( 983): #29 _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter ( 983): #30 _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)`

**To Reproduce**
1 - Type a place on searchbar and select one from results
2 - PlacePicker try to navigate to selected place but fail (stay in same place has before selection)
3 - See error in console logs

**Expected behavior**

**Flutter Doctor -v**
[✓] Flutter (Channel master, v1.18.0-6.0.pre.82, on Mac OS X 10.14.6 18G103, locale fr-BJ)
    • Flutter version 1.18.0-6.0.pre.82 at /Users/sadaq/flutter
    • Framework revision f35b673f2b (4 months ago), 2020-04-19 02:45:01 +0530
    • Engine revision a5e0b2f2f2
    • Dart version 2.9.0 (build 2.9.0-1.0.dev 5b19445d9c)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/sadaq/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • TECNO J8   • 192.168.0.101:5555 • android-arm64  • Android 7.1.2 (API 25)
    • Chrome     • chrome             • web-javascript • Google Chrome 84.0.4147.105
    • Web Server • web-server         • web-javascript • Flutter Tools

• No issues found!

**Comment by prapoorn-codeTru** [comment]
Hi,

even I am facing the same issue.

@easysoft-mobility Did you get any work around solution for this, please suggest if anything worked for you

**Comment by iamadeeel** [comment]
I am also facing same issue @prapoorn-codeTru Have you sort it out? Thanks in Advance?
